### ISSUE TITLE
After entering the verification code I get the following message

### ISSUE THREAD

**Issue by CaptainFuzzyFace** [jcasoft/GoogleCalendar-Skill#6]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/mycroft/skills/GoogleCalendar-Skill/__main__.py", line 88, in <module>
    start =  dateutil.parser.parse(start + " 00:00:00 LOC", tzinfos={"LOC": get_localzone()})
NameError: name 'get_localzone' is not defined

Happy to supply any info to help with the debug.

Also...
pi@mark_1:/opt/mycroft/skills $ sudo cp /home/pi/.mycroft/mycroft.conf /home/mycroft/.mycroft/mycroft.conf
cp: cannot stat ‘/home/pi/.mycroft/mycroft.conf’: No such file or directory

I guess these issues account for my mycroft.conf not having any GC items in it.

**Comment by jcasoft** [comment]
The problem has already been corrected, you can do "git pull" and try again.
or add "from tzlocal import get_localzone" at the begining of  __main__.py

**Comment by CaptainFuzzyFace** [comment]
Done that and all install steps have been run without error but I don't have any "GoogleCalendarSkill" section in my /home/mycroft/.mycroft/mycroft.conf . Also, I get these errors in my mycroft-cli-client session.

~~~~skill:117 - INFO - ATTEMPTING TO LOAD SKILL: GoogleCalendar-Skill with ID 751454374
~~~~oft.skills.core:load_skill:142 - ERROR - Failed to load skill: GoogleCalendar-Skill
File "/opt/mycroft/skills/GoogleCalendar-Skill/__init__.py", line 1235, in create_skill
return GoogleCalendarSkill()
File "/opt/mycroft/skills/GoogleCalendar-Skill/__init__.py", line 286, in __init__

**Comment by jcasoft** [comment]
Bug fixed, try now !
